print(len("hola mundo"))
print("hola mundo"[0])
print("hola mundo"[9])
#print("hola mundo"[10])
saludo="Hola mundo"
print(saludo)
print(len(saludo))
print(saludo[9])
print(saludo[-1]) 
#print(saludo[longitudsaludo])
print(saludo[2:7])
